<?php

use yii\helpers\Html;
use yii\helpers\url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use common\models\procurement\Division;
use common\models\procurement\Section;
use common\models\procurement\Project;
use common\models\procurement\Tmpitem;
use yii\helpers\Json;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model common\models\procurement\Purchaserequest */
/* @var $form yii\widgets\ActiveForm */
$BaseURL = $GLOBALS['frontend_base_uri'];
$con =  Yii::$app->db;
$command = $con->createCommand("SELECT `tbl_profile`.`user_id`,CONCAT(`tbl_profile`.`firstname`,', ', `tbl_profile`.`middleinitial` ,' ', `tbl_profile`.`lastname`, ' - ' , `tbl_profile`.`designation`) AS employeename
        FROM `tbl_profile`");
$employees = $command->queryAll();
$listEmployees = ArrayHelper::map($employees, 'user_id', 'employeename');

//var_dump(Json::encode($itemDataProvider));
//echo Yii::$app->session->getId();
$this->registerJsFile($BaseURL.'js/vue.js');
?>

<div class="purchaserequest-form" id="pr-app">
<p>{{ message }}</p>
<input type="checkbox" class="form-check-input bodm" name="balots[]" id="check2" value=1 v-on:click="counter += 1">
<?= Html::checkbox('agree', true, ['label' => 'I agree','v-on:click'=>'counter += 1']) ?>
<button v-on:click="counter += 1">Add 1</button>
  <p>The button above has been clicked {{ counter }} times.</p>
    <?php $form = ActiveForm::begin(['id' => 'create_pr']); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'section_id')->widget(Select2::classname(), [
                'data' => ArrayHelper::map(Section::find()->all(), 'section_id', 'name'),
                'options' => ['placeholder' => 'Select a section...', 'v-model' => 'message'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
            <?= $form->field($model, 'project_id')->widget(Select2::classname(), [
                'data' => ArrayHelper::map(Project::find()->all(), 'project_id', 'code'),
                'options' => ['placeholder' => 'Select a project ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'purchase_request_number')->textInput(['placeholder' => '<AutoGenerated>', 'readonly' => 'true', 'tabindex' => '-1']) ?>
            <?= $form->field($model, 'purchase_request_sai_number')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'purchase_request_date')->input("date", ['value' => $model->isNewRecord ? date("Y-m-d") : $model->purchase_request_date]) ?>
            <?= $form->field($model, 'purchase_request_saidate')->textInput()->input("date", ['value' => $model->isNewRecord ? date("Y-m-d") : $model->purchase_request_saidate]) ?>
        </div>

        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Items</h3>

                    <div class="box-tools pull-right">
                        <!--
                        <button type="button" class="btn btn-box-tool" data-toggle="collapse" data-target="#toggle-pane-pr-item"><i class="fa fa-minus"></i>
                        </button>
                        -->
                        <button type="button" class="btn btn-box-tool"><i class="fa fa-plus" id="plus-minus"></i>
                        </button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body collapse" id="toggle-pane-pr-item" style="">
                    <div class="row">
                        <div class=col-md-12>
                            <div class="item-table">
                                <!--table here-->
                            </div>
                            <div class="selected-item-table">
                                <!--table here-->
                            </div>
                            <!--
                                <div class="table-responsive collapse" id="myAdd">
                                    <table class="table no-margin">
                                        <thead>
                                            <tr>
                                                <th>Unit</th>
                                                <th>Item Description</th>
                                                <th>Unit Cost</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><a href="pages/examples/invoice.html">Box</a></td>
                                                <td>Call of Duty IV</td>
                                                <td>50,000</td>
                                                <td>
                                                    <button type="button" class="btn btn-primary btn-circle pull-right"><i class="fa fa-plus"></i></button>
                                                </td>
                                            <tr>
                                        </tbody>
                                    </table>
                                </div>
                                -->
                            <!-- /.table-responsive -->
                        </div>
                        <div class=col-md-12 style="margin-bottom: 10px;">
                            <?php /*
                            Html::button('Add Items  <i class="glyphicon glyphicon-list"></i>', [
                                //'disabled' => $model->status_id != 1 or !$isMember,
                                //'value' => Url::to(['create']),
                                'title' => 'Add Items',
                                'class' => 'btn btn-success btn-block',
                                'style' => 'margin-right: 6px; display: "";',
                                'id' => 'buttonmyAdd'
                            ])*/
                            ?>
                        </div>
                        <!--
                            <div class=col-md-12>
                            <div class="table-responsive">
                                <table class="table no-margin">
                                    <thead>
                                        <tr>
                                            <th>Unit</th>
                                            <th>Item Description</th>
                                            <th>Quantity</th>
                                            <th>Unit Cost</th>
                                            <th>Total Cost</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><a href="pages/examples/invoice.html">Box</a></td>
                                            <td>Call of Duty IV</td>
                                            <td class="editable-col-qty" contenteditable="true">1</span></td>
                                            <td>50,000</td>
                                            <td>50,000</td>
                                            <td>
                                                <button type="button" class="btn btn-danger btn-circle pull-right"><i class="fa fa-minus"></i></button>
                                            </td>
                                        <tr>
                                            <td><a href="pages/examples/invoice.html">Box</a></td>
                                            <td>Call of Duty IV</td>
                                            <td class="editable-col-qty" contenteditable="true">1</span></td>
                                            <td>50,000</td>
                                            <td>50,000</td>
                                            <td>
                                                <button type="button" class="btn btn-danger btn-circle pull-right"><i class="fa fa-minus"></i></button>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><a href="pages/examples/invoice.html">Box</a></td>
                                            <td>Call of Duty IV</td>
                                            <td class="editable-col-qty" contenteditable="true">1</span></td>
                                            <td>50,000</td>
                                            <td>50,000</td>
                                            <td>
                                                <button type="button" class="btn btn-danger btn-circle pull-right"><i class="fa fa-minus"></i></button>
                                            </td>
                                        </tr>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        -->

                    </div>

                    <div class="box-footer clearfix" style="">

                    </div>
                    <!-- /.box-footer -->
                </div>
                <!-- /.box-body -->
            </div>
        </div>


        <div class="col-md-12">
            <?= $form->field($model, 'purchase_request_purpose')->textarea(['rows' => 6]) ?>

            <?= $form->field($model, 'purchase_request_referrence_no')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'purchase_request_project_name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'purchase_request_location_project')->textInput(['maxlength' => true]) ?>
        </div>

        <div class="col-lg-12">
            <h5 data-step='11' data-intro='Select Assignatory.'>
                <h4 style="border-bottom: #1c1c1c 2px solid;text-transform: uppercase;margin-top: 0px">Assignatory</h4>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'purchase_request_requestedby_id')->widget(Select2::classname(), [
                'data' => $listEmployees,
                'id' => 'cboEmployee',
                'name' => 'cboEmployee',
                'language' => 'en',
                'options' => ['placeholder' => 'Select Employee'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'purchase_request_approvedby_id')->widget(Select2::classname(), [
                'data' => $listEmployees,
                'id' => 'cboApproved',
                'name' => 'cboApproved',
                'language' => 'en',
                'options' => ['placeholder' => 'Select Employee', 'value' => '2'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
        </div>
        <div class="col-lg-12">
            <h4 style="border-bottom: #1c1c1c 2px solid;text-transform: uppercase;"></h4>
        </div>

        <div class="form-group col-md-12">
            <?= Html::submitButton($model->isNewRecord ? 'Create Purchase Request' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>

</div>
<?php $this->registerJsFile($BaseURL.'js/purchaserequest/pr-app.js');?>


<style>
    .modal-dialog {
        width: 65%;
        margin-top: 0%;
    }

    .btn-circle {
        width: 20px;
        height: 20px;
        text-align: center;
        padding: 6px 0;
        font-size: 6px;
        line-height: 1.42;

    }

    div.item-table {
        max-height: 250px;
        overflow: auto;
    }

    div.selected-item-table {
        max-height: 250px;
        overflow: auto;
        margin-top: 10px;
    }
</style>